server:
  port: 8001
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/crudapp
    password: Vithal@7757
  jpa:
    properties:
      hibernate:
        dielect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 14879198622-cpgjptodifml0uq0rb375qf0g449brto.apps.googleusercontent.com
#            client-secret: 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

  security:
    user:
      name: Vithal
      password: Vithal@77578888